# readthedocs version
version: 2

build:
    os: ubuntu-22.04
tools:
    python: "mambaforge-22.9"
sphinx:
  builder: html
  configuration: doc/conf.py

python:
    version: 3.11
    install:
        - requirements: requirements/requirements-docs.txt
        - method: pip
          path: .
