# readthedocs version
version: 2

build:
    os: ubuntu-22.04
    tools:
      python: "3.11"
sphinx:
  builder: html
  configuration: doc/conf.py

python:
    install:
        - requirements: requirements/requirements-docs.txt
        - method: pip
          path: .
