# readthedocs version
version: 2

build:
    image: latest

sphinx:
  builder: html
  configuration: doc/conf.py

python:
    version: 3.9
    install:
        - requirements: requirements/requirements-docs.txt
        - method: pip
          path: .
