name: Mirror to Ebrains

# Configure the events that are going to trigger tha automated update of the mirror
on:
  push:
    branches: [ master ]

# Configure what will be updated
jobs:
  # set the job name
  to_ebrains:
    runs-on: ubuntu-latest
    steps:
      # this task will push the master branch of the source_repo (github) to the
      # destination_repo (ebrains gitlab)
      - name: syncmaster
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83
        # component owners need to set their own variables
        # the destination_repo format is
        # https://gitlab_service_account_name:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/name_of_mirror.git
        with:
          source_repo: "INM-6/viziphant "
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuralensemble/viziphant.git"
          destination_branch: "master"
      # this task will push all tags from the source_repo to the destination_repo
      - name: synctags
        uses: wei/git-sync@55c6b63b4f21607da0e9877ca9b4d11a29fc6d83
        with:
          source_repo: "INM-6/viziphant"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/neuralensemble/viziphant.git"
          destination_branch: "refs/tags/*"
